services:
  flask:
    build: ./flask
    container_name: flask
    env_file:
      - ./flask/app/.env
    environment:
      - APP_NAME=FlaskApp
    ports:
      - "127.0.0.1:4011:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
